### ISSUE TITLE
Getting notified of changes in Github

### ISSUE THREAD

**Issue by woudsma** [passionatepeople/coding-challenges#3]
Since I like lurking or sometimes viewing challenges + other peoples submissions, would it be possible to implement auto releases?
This way I would see the new challenge coming by in my Github feed every week.

I'd like to 'watch' certain events.
Releases or PR's would seem like a nice way to do this if I'm looking at the options here.

![Screenshot 2021-03-11 at 22 31 18](https://user-images.githubusercontent.com/6162978/110858328-3b93c500-82ba-11eb-8938-6a8cac3d1967.png)

Feel free to close this issue / feature request!

**Comment by arcanous** [comment]
Good idea!
